apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodevops-be-deployment
  namespace: hellodevopss-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellodevops-be
  template:
    metadata:
      labels:
        app: hellodevops-be
    spec:
      containers:
      - name: hellodevops-be
        image: u6687032/hellodevops-backend:latest    # ✅ ใช้ image ของคุณ
        imagePullPolicy: Always                       # ดึงอิมเมจใหม่ทุกครั้ง
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/hellodevops?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        - name: SPRING_DATASOURCE_USERNAME
          value: user_devops
        - name: SPRING_DATASOURCE_PASSWORD
          value: user1234
        - name: SPRING_FLYWAY_ENABLED
          value: "false"
        - name: SPRING_AUTOCONFIGURE_EXCLUDE
          value: "org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration"
---
apiVersion: v1
kind: Service
metadata:
  name: hellodevops-backend-service
  namespace: hellodevopss-app
spec:
  selector:
    app: hellodevops-be
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
