apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: muict-app-cert
  namespace: hellodevopss-app
spec:
  secretName: muict-app-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - hellodevops.muict.app