apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fe-ingress
  namespace: hellodevopss-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hellodevops.muict.app
      secretName: hellodevops-tls
  rules:
    - host: hellodevops.muict.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hellodevops-frontend-service
                port:
                  number: 80
