apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodevops-fe-deployment
  namespace: hellodevopss-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellodevops-fe
  template:
    metadata:
      labels:
        app: hellodevops-fe
    spec:
      containers:
      - name: hellodevops-fe
        image: u6687032/hello-devops-frontend:latest   # ✅ ใช้ image ของคุณ
        imagePullPolicy: Always                       # ดึงอิมเมจใหม่ทุกครั้ง
        ports:
        - containerPort: 80
#        env:
#        - name: VITE_API_URL
#          value: "/api"                               # ให้ frontend เรียกผ่าน ingress
---
apiVersion: v1
kind: Service
metadata:
  name: hellodevops-frontend-service
spec:
  selector:
    app: hellodevops-fe
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
